acme_test_start:
    pattern:  /
    defaults: { _controller: AcmeTestBundle:Default:index,name:test }
acme_test_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }
